//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class АвтозаправкиEntities : DbContext
    {
        public АвтозаправкиEntities()
            : base("name=АвтозаправкиEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Автозаправка> Автозаправка { get; set; }
        public virtual DbSet<Запись> Запись { get; set; }
        public virtual DbSet<Общая> Общая { get; set; }
        public virtual DbSet<Постоянные_клиенты> Постоянные_клиенты { get; set; }
        public virtual DbSet<Сервер> Сервер { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
        public virtual DbSet<Топливо> Топливо { get; set; }
        public virtual DbSet<Услуга> Услуга { get; set; }
        public virtual DbSet<Чек> Чек { get; set; }
        public virtual DbSet<ЧекТовар> ЧекТовар { get; set; }
        public virtual DbSet<ЧекУслуга> ЧекУслуга { get; set; }
    }
}
