//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автозаправка
    {
        public int Код { get; set; }
        public int Номер_автозаправки { get; set; }
        public string Номер_телефона { get; set; }
        public string Описание { get; set; }
        public Nullable<int> Номер_карточки_клиента { get; set; }
        public Nullable<int> Акции_на_товар { get; set; }
        public Nullable<int> Акции_на_услугу { get; set; }
        public Nullable<int> код_топлива { get; set; }
        public Nullable<int> количесвто_топлива { get; set; }
        public Nullable<int> код_товара { get; set; }
        public Nullable<int> количесвто_товаров { get; set; }
        public Nullable<int> код_услуги { get; set; }
        public Nullable<int> количесвто_услуг { get; set; }
        public int код_чека { get; set; }
    
        public virtual Топливо Топливо { get; set; }
        public virtual Товар Товар { get; set; }
        public virtual Услуга Услуга { get; set; }
        public virtual Чек Чек { get; set; }
        public virtual Постоянные_клиенты Постоянные_клиенты { get; set; }
        public virtual Акции_на_товар Акции_на_товар1 { get; set; }
        public virtual Акции_на_услугу Акции_на_услугу1 { get; set; }
        public virtual Общая Общая { get; set; }
    }
}
