//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Акции_на_товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Акции_на_товар()
        {
            this.Автозаправка = new HashSet<Автозаправка>();
        }
    
        public string Вид_акции { get; set; }
        public string Описание { get; set; }
        public Nullable<int> код_товара_на_акции { get; set; }
        public string Скидка_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Автозаправка> Автозаправка { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
