//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запись
    {
        public int Номер_записи { get; set; }
        public int Номер_автозаправки { get; set; }
        public int Код_топлива { get; set; }
    
        public virtual Автозаправка Автозаправка { get; set; }
        public virtual Топливо Топливо { get; set; }
    }
}
