//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Постоянные_клиенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Постоянные_клиенты()
        {
            this.Автозаправка = new HashSet<Автозаправка>();
            this.Чек = new HashSet<Чек>();
        }
    
        public int Номер_карточки_клиента { get; set; }
        public string ФИО_клиента { get; set; }
        public Nullable<int> Количество_посещений { get; set; }
        public Nullable<decimal> Средняя_потраченная_сумма { get; set; }
        public Nullable<int> Скидка_на_количество_посещений { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Автозаправка> Автозаправка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Чек> Чек { get; set; }
    }
}
