//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Постоянные_клиенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Постоянные_клиенты()
        {
            this.Чек = new HashSet<Чек>();
        }
    
        public int Номер_карточки_клиента { get; set; }
        public string ФИО_клиента { get; set; }
        public Nullable<int> Количество_посещений { get; set; }
        public decimal Средняя_потраченная_сумма { get; set; }
        public Nullable<int> Скидка_на_количество_посещений { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Чек> Чек { get; set; }
    }
}
