//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сервер
    {
        public int Код_записи { get; set; }
        public Nullable<System.DateTime> дата { get; set; }
        public decimal Средняя_прибыль_за_месяц { get; set; }
        public decimal Средняя_прибыль_за_топливо { get; set; }
        public decimal Общая_прибыль_за_месяц_по_услугам_и_товарам { get; set; }
        public int Общий_объём_израсходованного_топлива { get; set; }
    }
}
