//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Чек
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Чек()
        {
            this.ЧекТовар = new HashSet<ЧекТовар>();
            this.ЧекУслуга = new HashSet<ЧекУслуга>();
        }
    
        public int код_чека { get; set; }
        public Nullable<System.DateTime> дата { get; set; }
        public Nullable<int> код_топлива { get; set; }
        public Nullable<int> номер_карточки_клиента { get; set; }
        public decimal стоимость { get; set; }
    
        public virtual Постоянные_клиенты Постоянные_клиенты { get; set; }
        public virtual Топливо Топливо { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЧекТовар> ЧекТовар { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЧекУслуга> ЧекУслуга { get; set; }
    }
}
